a=int(input("Enter the number of a : "))
b=int(input("Enter the number of b : "))
print("\n1 for addition : \n")
print("2 for Sub : \n")
print("3 for Multi : \n")
print("4 for Divide : \n")
print("5 for Module : \n")
print("6 for Power : \n")
print("0 for exit : \n")
c=int(input("Enter the number of c : "))
match c:
        case 1:print(a+b)
        case 2:print(a-b)
        case 3:print(a*b)
        case 4:print(a/b)
        case 5:print(a%b)
        case 6:print(a**b)
